all:
	glslangValidator -V scene.glsl.frag -o scene.so.frag
	glslangValidator -V scene.glsl.vert -o scene.so.vert
	glslangValidator -V room.glsl.frag -o room.so.frag
	glslangValidator -V room.glsl.vert -o room.so.vert
