option(GIT_ThirdParty "git submodule the thirdparty" ON)
option(USE_OpenMP "Use CPU Multithread OpenMP" ON)
option(BUILD_BASE "Build libvulkanbase.so" ON)
option(BUILD_SimpleExamples "Build SimpleExamples" ON)
option(BUILD_AdvExamples "Build AdancedExamples" OFF)
option(BUILD_QtExamples "Build SimpleExamples" OFF)
set(QT_VERSION_MAJOR 5)
