if(BUILD_QtExamples MATCHES "ON")
    find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Widgets REQUIRED)
else()
    find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Widgets REQUIRED)
    if(Qt5_FOUND)
        message("Auto Find Qt${QT_VERSION_MAJOR}. Qt${QT_VERSION_MAJOR} is enabled")
        set(BUILD_QtExamples ON)
    else()
        message("Qt${QT_VERSION_MAJOR} not Found, you need to manually set your Qt Path. And try cmake .. -DBUILD_QtExamples=ON")
    endif()
endif()
