if(BUILD_QtExamples MATCHES "ON")
    find_package(Qt5 COMPONENTS Widgets REQUIRED)
else()
    find_package(Qt5 COMPONENTS Widgets)
    if(Qt5_FOUND)
        message("Auto Find Qt5. Qt5 is enabled")
        set(BUILD_QtExamples ON)
    else()
        message("Qt5 not Found, you need to manually set your Qt Path. And try cmake .. -DBUILD_QtExamples=ON")
    endif()
endif()
