find_package(Qt6 COMPONENTS Widgets)

if (Qt6_FOUND)
    set(QT_VERSION_MAJOR 6)
    set(BUILD_QtExamples ON)
    message("Find QT6")
else()
    find_package(Qt5 COMPONENTS Widgets)
    if (Qt5_FOUND)
        set(QT_VERSION_MAJOR 5)
        set(BUILD_QtExamples ON)
        message("Find QT5")
    else()
        message("Qt${QT_VERSION_MAJOR} not Found, you need to manually set your Qt Path. And try cmake .. -DBUILD_QtExamples=ON")
    endif()
endif()

return()
