Find_Package(Vulkan)
if(Vulkan_FOUND)
    message("Vulkan has been found in")
    message(${Vulkan_INCLUDE_DIRS})
    message(${Vulkan_LIBRARIES})
    include_directories(${Vulkan_INCLUDE_DIRS})
    link_directories(${Vulkan_LIBRARY})
else()
    message("Vulkan not found.Do you set your VulkanSdk PATH correctly?")
    message("link and include /usr/local instead")
    include_directories(/usr/local/include)
    link_directories(/usr/local/lib)
    if(UNIX)
        set(Vulkan_LIBRARIES vulkan)
    else()
        set(Vulkan_LIBRARIES vulkan-1)
    endif()
endif()
