if(BUILD_AdvExamples MATCHES ON)
    find_package(Assimp REQUIRED)
else()
    find_package(Assimp)
    if(Assimp_FOUND)
        message("Found Assimp,enable Advanced Examples Build.")
        set(BUILD_AdvExamples ON)
    else()
        message("Assimp not found, Advanced Examples will not be built.")
        message("or you manually set path.And try 'cmake .. -DBUILD_AdvExamples=ON' ")
    endif()
endif()
