if(BUILD_AdvExamples MATCHES ON)
    find_package(assimp REQUIRED)
    add_definitions(-DBUILD_ASSIMP)
else()
    find_package(assimp)
    if(assimp_FOUND)
        message("Found Assimp,enable Advanced Examples Build.")
        set(BUILD_AdvExamples ON)
        add_definitions(-DBUILD_ASSIMP)
    else()
        message("Assimp not found, Advanced Examples will not be built.")
        message("or you manually set path.And try 'cmake .. -DBUILD_AdvExamples=ON' ")
    endif()
endif()
