all:
	glslangValidator -V scene.glsl.frag -o scene.so.frag
	glslangValidator -V scene.glsl.vert -o scene.so.vert
	glslangValidator -V plane.glsl.frag -o plane.so.frag
	glslangValidator -V plane.glsl.vert -o plane.so.vert
	glslangValidator -V shadow.glsl.frag -o shadow.so.frag
	glslangValidator -V shadow.glsl.vert -o shadow.so.vert
